spring.application.name=CRUD
#forma de update das entidades
spring.jpa.hibernate.ddl-auto=update
#URL de conex�o e comando de cria��o
spring.datasource.url=jdbc:mysql://localhost:3306/CRUD?createDatabaseIfNotExist=true
#Usu�rio
spring.datasource.username=root
#Senha
spring.datasource.password=laboratorio

